<a href="<?= $this->getUrl('smart'); ?>"><span>Back</span></a>
<form 
  action="<?= $block->getFormAction(); ?>" 
  method="post" 
  data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
  data-mage-init='{"validation":{}}'
  >

  <fieldset class="fieldset">
    <div class="field name required">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
        <div class="control">
            <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
        </div>
    </div>
    <div class="field email required">
        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
        <div class="control">
            <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
  </fieldset>
</form>